---
apiVersion: v1
kind: Service
metadata:
  name: webhook-svc
  labels:
    app: webhook-tester
spec:
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: webhook-tester
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: webhook-tester
spec:
  replicas: 1
  selector:
    app: webhook-tester
  template:
    metadata:
      labels:
        app: webhook-tester
    spec:
      containers:
      - name: webhook-tester
        image: index.caicloud.io/caicloud/webhook-tester
        ports:
        - containerPort: 3000